Gem::Specification.new do |s|
  s.name              = "refinerycms-submissions"
  s.version           = "1.0"
  s.date              = "2012-02-01"
  s.summary           = "Contact submissions gem for Refinery with akismet spam filter and extra contact fields."
  s.description       = "Contact submission handling functionality extracted from Refinery CMS to allow you to have a contact form and manage submissions in the Refinery backend. Also includes akismet spam filtering"
  s.url               = "http://github.com/jrissler/refinerycms-submissions"
  s.email             = "james@railsbits.com"
  s.authors           = ["James Rissler"]
  s.require_paths     = %w(lib)
  s.ignore_pattern    = ["tmp/*", "script/*"]

  s.files             = [
    'refinerycms-submissions.gemspec',
    'app',
    'app/controllers',
    'app/controllers/submissions_controller.rb',
    'app/controllers/admin',
    'app/controllers/admin/submissions_controller.rb',
    'app/controllers/admin/submission_settings_controller.rb',
    'app/views',
    'app/views/submissions',
    'app/views/submissions/thank_you.html.erb',
    'app/views/submissions/new.html.erb',
    'app/views/submission_mailer',
    'app/views/submission_mailer/confirmation.html.erb',
    'app/views/submission_mailer/notification.html.erb',
    'app/views/admin',
    'app/views/admin/submissions',
    'app/views/admin/submissions/show.html.erb',
    'app/views/admin/submissions/_submenu.html.erb',
    'app/views/admin/submissions/index.html.erb',
    'app/views/admin/submissions/_submission.html.erb',
    'app/views/admin/submission_settings',
    'app/views/admin/submission_settings/_notification_recipients_form.html.erb',
    'app/views/admin/submission_settings/_confirmation_email_form.html.erb',
    'app/views/admin/submission_settings/edit.html.erb',
    'app/helpers',
    'app/helpers/submissions_helper.rb',
    'app/models',
    'app/models/submission_setting.rb',
    'app/models/submission.rb',
    'app/mailers',
    'app/mailers/submission_mailer.rb',
    'spec',
    'spec/models',
    'spec/models/submission_spec.rb',
    'features',
    'features/support',
    'features/support/paths.rb',
    'features/support/factories.rb',
    'features/manage_submissions.feature',
    'features/create_submissions.feature',
    'features/step_definitions',
    'features/step_definitions/submission_steps.rb',
    'lib',
    'lib/gemspec.rb',
    'lib/submissions.rb',
    'lib/generators',
    'lib/generators/refinerycms_submissions_generator.rb',
    'lib/refinerycms-submissions.rb',
    'db',
    'db/migrate',
    'db/migrate/20101208082840_create_submissions.rb',
    'db/seeds',
    'db/seeds/pages_for_submissions.rb',
    'readme.md',
    'license.md',
    'config',
    'config/locales',
    'config/locales/sk.yml',
    'config/locales/cs.yml',
    'config/locales/bg.yml',
    'config/locales/nl.yml',
    'config/locales/sl.yml',
    'config/locales/sv.yml',
    'config/locales/ru.yml',
    'config/locales/pt-BR.yml',
    'config/locales/zh-CN.yml',
    'config/locales/lt.yml',
    'config/locales/da.yml',
    'config/locales/en-GB.yml',
    'config/locales/it.yml',
    'config/locales/lolcat.yml',
    'config/locales/nb.yml',
    'config/locales/en.yml',
    'config/locales/lv.yml',
    'config/locales/fr.yml',
    'config/locales/de.yml',
    'config/locales/es.yml',
    'config/locales/pl.yml',
    'config/routes.rb'
  ]
  s.require_path = 'lib'
end

